modLoader="javafml"
loaderVersion="[47,)"
license="MIT"

[[mods]]
modId="tikfinity"
version="1.0.0"
displayName="JDO tikfinity"
updateJSONURL="https://example.com/update.json"
displayURL="https://example.com"
logoFile="logo.png"
credits="Thanks to the Minecraft Forge team!"
authors="JDO"
description='''
Mob created by JDO for link to tikfinity
'''

[[mixins]]
config = "mixins.tikfinity.json"